import { FormEvent, useEffect, useState } from 'react';
import { BadgeDollarSign, CalendarClock, Download, FileClock, ListChecks, Plus, RefreshCw, RotateCcw, Trash2, UserRoundCheck } from 'lucide-react';
import { adjustCurrentWeekDuration, createEligibilityEntry, createLedgerEntry, createTeamEvent, deleteEligibilityEntry, downloadLedgerExport, downloadRecordsExport, fetchAdminWeeklyAdjustments, fetchAdminWeeklyReports, fetchEligibilityEntries, fetchLedgerEntries, fetchLedgerSummary, fetchLedgerTrend, fetchTeamEvents, reverseLedgerEntry, updateEligibilityEntry, updateTeamEvent, voidLedgerEntry } from '@/lib/api';
import { getShanghaiIsoWeek, isoWeekToShanghaiMonday, isIsoWeek } from '@/lib/week';
import { openExternalUrl } from '@/lib/desktop';
import type { AdminDurationAdjustment, AdminWeeklyReportsResponse, MemberEligibilityEntry, TeamEventItem, TeamLedgerEntry, TeamLedgerSummary, TeamLedgerTrendItem } from '@/types';

type AdminTab = 'eligibility' | 'ledger' | 'events' | 'attendance' | 'weeklyReports';
const formatCents = (cents: number) => `¥${(cents / 100).toFixed(2)}`;
const formatHours = (seconds: number) => `${Math.floor(seconds / 3600)}小时${Math.floor(seconds % 3600 / 60)}分`;
const saveDownload = ({ blob, filename }: { blob: Blob; filename: string }) => { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = filename; anchor.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };

export const AdminOperationsPanel = ({ onNotice }: { onNotice: (message: string) => void }) => {
  const [tab, setTab] = useState<AdminTab>('eligibility');
  const [busy, setBusy] = useState(false);
  const [week, setWeek] = useState(getShanghaiIsoWeek);
  const [eligibility, setEligibility] = useState<MemberEligibilityEntry[]>([]);
  const [ledger, setLedger] = useState<TeamLedgerEntry[]>([]);
  const [ledgerSummary, setLedgerSummary] = useState<TeamLedgerSummary | null>(null);
  const [trend, setTrend] = useState<TeamLedgerTrendItem[]>([]);
  const [events, setEvents] = useState<TeamEventItem[]>([]);
  const [adjustments, setAdjustments] = useState<AdminDurationAdjustment[]>([]);
  const [weeklyReports, setWeeklyReports] = useState<AdminWeeklyReportsResponse | null>(null);
  const [studentId, setStudentId] = useState(''); const [realName, setRealName] = useState(''); const [eligibilityNote, setEligibilityNote] = useState('');
  const [ledgerType, setLedgerType] = useState<'income' | 'expense'>('expense'); const [ledgerAmount, setLedgerAmount] = useState(''); const [ledgerCategory, setLedgerCategory] = useState(''); const [ledgerNote, setLedgerNote] = useState('');
  const [eventTitle, setEventTitle] = useState(''); const [eventAt, setEventAt] = useState(''); const [eventDescription, setEventDescription] = useState('');
  const [targetUsername, setTargetUsername] = useState(''); const [adjustmentOperation, setAdjustmentOperation] = useState<'add' | 'subtract'>('add'); const [adjustmentHours, setAdjustmentHours] = useState(''); const [adjustmentReason, setAdjustmentReason] = useState('');

  const load = async (target = tab) => {
    setBusy(true);
    try {
      if (target === 'eligibility') setEligibility((await fetchEligibilityEntries()).items);
      if (target === 'ledger') { const [entries, summary, nextTrend] = await Promise.all([fetchLedgerEntries(), fetchLedgerSummary(), fetchLedgerTrend({ granularity: 'week' })]); setLedger(entries.items); setLedgerSummary(summary); setTrend(nextTrend.items); }
      if (target === 'events') setEvents((await fetchTeamEvents(true)).items);
      if (target === 'attendance') { if (!isIsoWeek(week)) throw new Error('周格式应为 YYYY-Www。'); setAdjustments((await fetchAdminWeeklyAdjustments(week)).items); }
      if (target === 'weeklyReports') { if (!isIsoWeek(week)) throw new Error('周格式应为 YYYY-Www。'); setWeeklyReports(await fetchAdminWeeklyReports(week)); }
    } catch (error) { onNotice(error instanceof Error ? error.message : '管理员功能加载失败。'); }
    finally { setBusy(false); }
  };
  useEffect(() => { void load(); }, [tab]);
  const switchTab = (next: AdminTab) => { setTab(next); };
  const run = async (action: () => Promise<void>) => { setBusy(true); try { await action(); } catch (error) { onNotice(error instanceof Error ? error.message : '操作失败。'); } finally { setBusy(false); } };
  const addEligibility = (event: FormEvent) => { event.preventDefault(); void run(async () => { await createEligibilityEntry({ studentId: studentId.trim(), realName: realName.trim(), note: eligibilityNote.trim() || undefined }); setStudentId(''); setRealName(''); setEligibilityNote(''); await load('eligibility'); onNotice('成员资格已新增。'); }); };
  const addLedger = (event: FormEvent) => { event.preventDefault(); const yuan = Number(ledgerAmount); if (!Number.isFinite(yuan) || yuan <= 0) return onNotice('金额必须大于 0。'); void run(async () => { await createLedgerEntry({ occurredAt: new Date().toISOString(), type: ledgerType, amountCents: Math.round(yuan * 100), category: ledgerCategory.trim(), note: ledgerNote.trim() || undefined }); setLedgerAmount(''); setLedgerCategory(''); setLedgerNote(''); await load('ledger'); onNotice('账本条目已新增。'); }); };
  const addEvent = (event: FormEvent) => { event.preventDefault(); if (!eventAt) return onNotice('请选择事务时间。'); void run(async () => { await createTeamEvent({ title: eventTitle.trim(), description: eventDescription.trim() || undefined, eventAt: new Date(eventAt).toISOString(), status: 'planned' }); setEventTitle(''); setEventDescription(''); await load('events'); onNotice('团队事务已创建。'); }); };
  const addAdjustment = (event: FormEvent) => { event.preventDefault(); const hours = Number(adjustmentHours); if (!Number.isFinite(hours) || hours <= 0) return onNotice('调整时长必须大于 0 小时。'); void run(async () => { await adjustCurrentWeekDuration({ username: targetUsername.trim(), operation: adjustmentOperation, durationSeconds: Math.round(hours * 3600), reason: adjustmentReason.trim() || undefined }); setAdjustmentHours(''); setAdjustmentReason(''); await load('attendance'); onNotice('时长调整已写入独立审计记录，不会改变积分。'); }); };
  const openWeeklyReport = async (url: string) => { try { await openExternalUrl(url); } catch (error) { onNotice(error instanceof Error ? error.message : '无法打开公开周报。'); } };

  return <section className="admin-operations blue-card"><header><div><p className="eyebrow">ADMIN OPERATIONS</p><h2>团队业务管理</h2><p>所有动作由服务端 JWT 与团队边界再次校验；危险操作会要求确认。</p></div><button className="admin-reload" onClick={() => void load()} disabled={busy}><RefreshCw size={14} />刷新</button></header><nav className="admin-tabs">{([{ id: 'eligibility', label: '成员资格', icon: UserRoundCheck }, { id: 'ledger', label: '团队账本', icon: BadgeDollarSign }, { id: 'events', label: '团队事务', icon: CalendarClock }, { id: 'attendance', label: '时长审计', icon: FileClock }, { id: 'weeklyReports', label: '周报状态', icon: ListChecks }] as const).map(({ id, label, icon: Icon }) => <button className={tab === id ? 'active' : ''} key={id} onClick={() => switchTab(id)}><Icon size={15} />{label}</button>)}</nav>
    {(tab === 'attendance' || tab === 'weeklyReports') ? <div className="admin-week-row"><label>ISO 周<input value={week} onChange={(event) => setWeek(event.target.value.toUpperCase())} maxLength={8} /></label><button onClick={() => void load(tab)}>查询</button></div> : null}
    {tab === 'eligibility' ? <div className="admin-operation-grid"><form onSubmit={addEligibility} className="admin-inline-form"><h3>新增资格名单</h3><input value={studentId} onChange={(event) => setStudentId(event.target.value)} placeholder="12 位学号" pattern="\d{12}" required /><input value={realName} onChange={(event) => setRealName(event.target.value)} placeholder="真实姓名" required /><input value={eligibilityNote} onChange={(event) => setEligibilityNote(event.target.value)} placeholder="备注（可选）" /><button disabled={busy}><Plus size={14} />新增</button></form><div className="admin-operation-list">{eligibility.map((item) => <div key={item.id}><span><strong>{item.realName}</strong> · {item.studentId}<small>{item.note || '无备注'}</small></span><button disabled={busy} onClick={() => void run(async () => { await updateEligibilityEntry(item.id, { status: item.status === 'allowed' ? 'blocked' : 'allowed' }); await load('eligibility'); })}>{item.status === 'allowed' ? '禁用' : '允许'}</button><button className="soft-danger" disabled={busy} onClick={() => { if (window.confirm(`删除 ${item.realName} 的资格名单？此操作不可恢复。`)) void run(async () => { await deleteEligibilityEntry(item.id); await load('eligibility'); }); }}><Trash2 size={13} /></button></div>)}</div></div> : null}
    {tab === 'ledger' ? <div className="admin-operation-grid"><form onSubmit={addLedger} className="admin-inline-form"><h3>新增账本条目</h3><select value={ledgerType} onChange={(event) => setLedgerType(event.target.value as typeof ledgerType)}><option value="expense">支出</option><option value="income">收入</option></select><input type="number" min="0.01" step="0.01" value={ledgerAmount} onChange={(event) => setLedgerAmount(event.target.value)} placeholder="金额（元）" required /><input value={ledgerCategory} onChange={(event) => setLedgerCategory(event.target.value)} placeholder="分类" required /><input value={ledgerNote} onChange={(event) => setLedgerNote(event.target.value)} placeholder="备注（可选）" /><button disabled={busy}><Plus size={14} />记账</button></form><div className="ledger-summary">收入 {formatCents(ledgerSummary?.incomeCents || 0)} · 支出 {formatCents(ledgerSummary?.expenseCents || 0)} · 结余 {formatCents(ledgerSummary?.netCents || 0)}<button onClick={() => void run(async () => { saveDownload(await downloadLedgerExport()); })}><Download size={13} />导出 CSV</button></div><div className="admin-operation-list">{ledger.map((item) => <div key={item.id}><span><strong>{item.type === 'income' ? '收入' : '支出'} {formatCents(item.amountCents)}</strong> · {item.category}<small>{item.status === 'voided' ? `已作废：${item.voidReason || '无原因'}` : item.note || '无备注'}</small></span>{item.status === 'active' ? <><button disabled={busy} onClick={() => { const reason = window.prompt('作废原因（可选）') ?? undefined; if (reason !== undefined) void run(async () => { await voidLedgerEntry(item.id, reason); await load('ledger'); }); }}>作废</button><button disabled={busy} onClick={() => void run(async () => { await reverseLedgerEntry(item.id, { note: '管理员创建冲正' }); await load('ledger'); })}><RotateCcw size={13} />冲正</button></> : null}</div>)}</div>{trend.length ? <p className="admin-hint">趋势：{trend.map((item) => `${item.bucketKey} ${formatCents(item.netCents)}`).join(' · ')}</p> : null}</div> : null}
    {tab === 'events' ? <div className="admin-operation-grid"><form onSubmit={addEvent} className="admin-inline-form"><h3>发布团队事务</h3><input value={eventTitle} onChange={(event) => setEventTitle(event.target.value)} placeholder="事务标题" minLength={2} required /><input type="datetime-local" value={eventAt} onChange={(event) => setEventAt(event.target.value)} required /><input value={eventDescription} onChange={(event) => setEventDescription(event.target.value)} placeholder="说明（可选）" /><button disabled={busy}><Plus size={14} />发布</button></form><div className="admin-operation-list">{events.map((item) => <div key={item.id}><span><strong>{item.title}</strong> · {new Date(item.eventAt).toLocaleString('zh-CN')}<small>{item.description || '无说明'}</small></span><select value={item.status} disabled={busy} onChange={(event) => void run(async () => { await updateTeamEvent(item.id, { status: event.target.value as TeamEventItem['status'] }); await load('events'); })}><option value="planned">计划中</option><option value="done">已完成</option><option value="cancelled">已取消</option></select></div>)}</div></div> : null}
    {tab === 'attendance' ? <div className="admin-operation-grid"><form onSubmit={addAdjustment} className="admin-inline-form"><h3>当前周时长调整</h3><input value={targetUsername} onChange={(event) => setTargetUsername(event.target.value)} placeholder="成员用户名" required /><select value={adjustmentOperation} onChange={(event) => setAdjustmentOperation(event.target.value as typeof adjustmentOperation)}><option value="add">增加时长</option><option value="subtract">扣除时长</option></select><input type="number" min="0.01" step="0.01" value={adjustmentHours} onChange={(event) => setAdjustmentHours(event.target.value)} placeholder="小时" required /><input value={adjustmentReason} onChange={(event) => setAdjustmentReason(event.target.value)} placeholder="调整原因" /><button disabled={busy}><Plus size={14} />写入审计</button></form><div className="ledger-summary">调整不会改动积分或原始打卡记录。<button onClick={() => void run(async () => saveDownload(await downloadRecordsExport({ weekKey: isoWeekToShanghaiMonday(week) }))) }><Download size={13} />导出本周记录</button></div><div className="admin-operation-list">{adjustments.length ? adjustments.map((item) => <div key={item.adjustmentId}><span><strong>{item.displayName} · {item.operation === 'add' ? '增加' : '扣除'} {formatHours(item.durationSeconds)}</strong><small>{item.reason || '未填写原因'} · {new Date(item.createdAt).toLocaleString('zh-CN')}</small></span></div>) : <p className="admin-empty">暂无调整记录。</p>}</div></div> : null}
    {tab === 'weeklyReports' ? <div className="admin-operation-list">{weeklyReports?.items.map((item) => <div key={item.member.userId}><span><strong>{item.member.displayName} · {item.status === 'generated' ? '已生成' : item.status === 'missing' ? '缺少日报' : '等待处理'}</strong><small>{item.dailyLogCount} 篇日报{item.attendanceAdjustment.adjustmentsCount ? ` · 含 ${item.attendanceAdjustment.adjustmentsCount} 条时长调整` : ''}</small></span>{item.rawUrl ? <button onClick={() => void openWeeklyReport(item.rawUrl!)}>查看正文</button> : null}</div>) || <p className="admin-empty">暂无周报状态。</p>}</div> : null}
  </section>;
};
