export const ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',
  USER_DISABLED: 'USER_DISABLED',
  ATTENDANCE_ALREADY_CHECKED_IN: 'ATTENDANCE_ALREADY_CHECKED_IN',
  ATTENDANCE_NO_ACTIVE_SESSION: 'ATTENDANCE_NO_ACTIVE_SESSION',
  ATTENDANCE_NETWORK_NOT_ALLOWED: 'ATTENDANCE_NETWORK_NOT_ALLOWED',
  ATTENDANCE_SESSION_INVALIDATED: 'ATTENDANCE_SESSION_INVALIDATED',
  ATTENDANCE_CROSS_TEAM_FORBIDDEN: 'ATTENDANCE_CROSS_TEAM_FORBIDDEN'
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
